version: "3.8"

services:
  springboot_server:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      # Database
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_DB_PROD_URL=${SPRING_DB_PROD_URL}
      # RabbitMQ
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      # Misc
      - IMAGE_NAME=${IMAGE_NAME}
      - TZ=Europe/Warsaw
    networks:
      - webnet_resume

  celery_worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - SCHEDULER_API_URL=${SCHEDULER_API_URL}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - LATEX_TEMPLATE_DIR=./cv-tex-templates
      - TZ=Europe/Warsaw
    depends_on:
      - springboot_server
    networks:
      - webnet_resume

networks:
  webnet_resume:
  outer_traefik_network:
    name: ${NETWORK_NAME}
    external: true
