version: "3.8"

services:
  springboot_server:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - SPRING_CV_API_LOGIN=${SPRING_CV_API_LOGIN}
      - SPRING_CV_API_PASSWORD=${SPRING_CV_API_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_DB_PROD_URL=${SPRING_DB_PROD_URL}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - IMAGE_NAME=${IMAGE_NAME}
      - TZ=Europe/Warsaw
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${NETWORK_NAME}"
      - "traefik.http.routers.${IMAGE_NAME}.rule=Host(`${HOST_IP}`) && PathPrefix(`/${IMAGE_NAME}`)"
      - "traefik.http.services.${IMAGE_NAME}.loadbalancer.server.port=8080"
    networks:
      - webnet_resume
      - outer_traefik_network

  celery_worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - SCHEDULER_API_URL=${SCHEDULER_API_URL}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - LATEX_TEMPLATE_DIR=./cv-tex-templates
      - TZ=Europe/Warsaw
    depends_on:
      - springboot_server
    networks:
      - webnet_resume

networks:
  webnet_resume:
  outer_traefik_network:
    name: ${NETWORK_NAME}
    external: true
