version: "3.8"

services:
  php_server:
    build:
      context: ./client
      dockerfile: Dockerfile
    #Need specific conainer name for migration, TODO build it bw
    container_name: ${APP_DEPLOYMENT_NAME}
    environment:
      - APP_NAME=JSON Resume Builder
      - APP_DEPLOYMENT_NAME=${APP_DEPLOYMENT_NAME}
      - HOST_IP=${HOST_IP}
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      # Laravel specific env variables
      - SESSION_DRIVER=database
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=database
      - QUEUE_CONNECTION=rabbitmq
      # RabbitMQ environment variables
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - TZ=Europe/Warsaw
      - SCHEDULER_API_URL=${SCHEDULER_API_URL}
    volumes:
      - laravel_public:/var/www/public
    networks:
      - webnet_resume

  nginx:
    image: nginx:latest
    volumes:
      - laravel_public:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - traefik.docker.network=${NETWORK_NAME}
      - "traefik.http.routers.${APP_DEPLOYMENT_NAME}.rule=Host(`${HOST_IP}`) && PathPrefix(`/${APP_DEPLOYMENT_NAME}`)"
      - "traefik.http.services.${APP_DEPLOYMENT_NAME}.loadbalancer.server.port=80"
    depends_on:
      - php_server
    networks:
      - webnet_resume
      - outer_traefik_network

  celery_worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - SCHEDULER_API_URL=${SCHEDULER_API_URL}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - LATEX_TEMPLATE_DIR=./cv-tex-templates
      - TZ=Europe/Warsaw
    depends_on:
      - php_server
    networks:
      - webnet_resume

networks:
  webnet_resume:
  outer_traefik_network:
    name: ${NETWORK_NAME}
    external: true
volumes:
  laravel_public:
