version: "3.8"

services:
  php_server:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/var/www
    environment:
      - APP_NAME=JSON Resume Builder
      - APP_DEPLOYMENT_NAME=${APP_DEPLOYMENT_NAME}
      - HOST_IP=${HOST_IP}
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      # Other Laravel specific env variables
      - SESSION_DRIVER=database
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=database
      - QUEUE_CONNECTION=rabbitmq
      # RabbitMQ environment variables
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - TZ=Europe/Warsaw
      - SCHEDULER_API_URL=${SCHEDULER_API_URL}
    ports:
      - "9000:9000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_DEPLOYMENT_NAME}.rule=Host(`${HOST_IP}`) && PathPrefix(`/${APP_DEPLOYMENT_NAME}`)"
      - "traefik.http.services.${APP_DEPLOYMENT_NAME}.loadbalancer.server.port=9000"
    networks:
      - docker0
      - webnet-resume

  celery_worker:
    build:
      context: ./worker
      dockerfile: Dockerfile # Replace with the actual Dockerfile name if it's different
    volumes:
      - ./worker:/usr/src/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - SCHEDULER_API_URL=${SCHEDULER_API_URL}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - LATEX_TEMPLATE_DIR=./cv-tex-templates
      - TZ=Europe/Warsaw
    depends_on:
      - php_server
    networks:
      - webnet-resume

networks:
  webnet-resume:
  docker0:
    external: true
